'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WsRp3
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.approuter.com/connectors/wsdl", ConfigurationName:="WsRp3.Proporcionar_servicioPort")>  _
    Public Interface Proporcionar_servicioPort
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación Proporcionar_servicio no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Proporcionar_servicio(ByVal request As WsRp3.Proporcionar_servicioRequest) As WsRp3.Proporcionar_servicioResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function Proporcionar_servicioAsync(ByVal request As WsRp3.Proporcionar_servicioRequest) As System.Threading.Tasks.Task(Of WsRp3.Proporcionar_servicioResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://ln.gesalm.integracion.pronaca.com.ec")>  _
    Partial Public Class SendBalanceData
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://ln.gesalm.integracion.pronaca.com.ec")>  _
    Partial Public Class SendBalanceDataResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private sendBalanceDataResultField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property SendBalanceDataResult() As String
            Get
                Return Me.sendBalanceDataResultField
            End Get
            Set
                Me.sendBalanceDataResultField = value
                Me.RaisePropertyChanged("SendBalanceDataResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Proporcionar_servicioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ln.gesalm.integracion.pronaca.com.ec", Order:=0)>  _
        Public SendBalanceData As WsRp3.SendBalanceData
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendBalanceData As WsRp3.SendBalanceData)
            MyBase.New
            Me.SendBalanceData = SendBalanceData
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Proporcionar_servicioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://ln.gesalm.integracion.pronaca.com.ec", Order:=0)>  _
        Public SendBalanceDataResponse As WsRp3.SendBalanceDataResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SendBalanceDataResponse As WsRp3.SendBalanceDataResponse)
            MyBase.New
            Me.SendBalanceDataResponse = SendBalanceDataResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Proporcionar_servicioPortChannel
        Inherits WsRp3.Proporcionar_servicioPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Proporcionar_servicioPortClient
        Inherits System.ServiceModel.ClientBase(Of WsRp3.Proporcionar_servicioPort)
        Implements WsRp3.Proporcionar_servicioPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRp3_Proporcionar_servicioPort_Proporcionar_servicio(ByVal request As WsRp3.Proporcionar_servicioRequest) As WsRp3.Proporcionar_servicioResponse Implements WsRp3.Proporcionar_servicioPort.Proporcionar_servicio
            Return MyBase.Channel.Proporcionar_servicio(request)
        End Function
        
        Public Function Proporcionar_servicio(ByVal SendBalanceData As WsRp3.SendBalanceData) As WsRp3.SendBalanceDataResponse
            Dim inValue As WsRp3.Proporcionar_servicioRequest = New WsRp3.Proporcionar_servicioRequest()
            inValue.SendBalanceData = SendBalanceData
            Dim retVal As WsRp3.Proporcionar_servicioResponse = CType(Me,WsRp3.Proporcionar_servicioPort).Proporcionar_servicio(inValue)
            Return retVal.SendBalanceDataResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsRp3_Proporcionar_servicioPort_Proporcionar_servicioAsync(ByVal request As WsRp3.Proporcionar_servicioRequest) As System.Threading.Tasks.Task(Of WsRp3.Proporcionar_servicioResponse) Implements WsRp3.Proporcionar_servicioPort.Proporcionar_servicioAsync
            Return MyBase.Channel.Proporcionar_servicioAsync(request)
        End Function
        
        Public Function Proporcionar_servicioAsync(ByVal SendBalanceData As WsRp3.SendBalanceData) As System.Threading.Tasks.Task(Of WsRp3.Proporcionar_servicioResponse)
            Dim inValue As WsRp3.Proporcionar_servicioRequest = New WsRp3.Proporcionar_servicioRequest()
            inValue.SendBalanceData = SendBalanceData
            Return CType(Me,WsRp3.Proporcionar_servicioPort).Proporcionar_servicioAsync(inValue)
        End Function
    End Class
End Namespace
