'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace Rp3Ws
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Proporcionar_servicioBinding", [Namespace]:="http://www.approuter.com/connectors/wsdl")>  _
    Partial Public Class Proporcionar_servicioService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Proporcionar_servicioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Servidor.My.MySettings.Default.Servidor_Rp3Ws_Proporcionar_servicioService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Proporcionar_servicioCompleted As Proporcionar_servicioCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function Proporcionar_servicio(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://ln.gesalm.integracion.pronaca.com.ec")> ByVal SendBalanceData As SendBalanceData) As <System.Xml.Serialization.XmlElementAttribute("SendBalanceDataResponse", [Namespace]:="http://ln.gesalm.integracion.pronaca.com.ec")> SendBalanceDataResponse
            Dim results() As Object = Me.Invoke("Proporcionar_servicio", New Object() {SendBalanceData})
            Return CType(results(0),SendBalanceDataResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Proporcionar_servicioAsync(ByVal SendBalanceData As SendBalanceData)
            Me.Proporcionar_servicioAsync(SendBalanceData, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Proporcionar_servicioAsync(ByVal SendBalanceData As SendBalanceData, ByVal userState As Object)
            If (Me.Proporcionar_servicioOperationCompleted Is Nothing) Then
                Me.Proporcionar_servicioOperationCompleted = AddressOf Me.OnProporcionar_servicioOperationCompleted
            End If
            Me.InvokeAsync("Proporcionar_servicio", New Object() {SendBalanceData}, Me.Proporcionar_servicioOperationCompleted, userState)
        End Sub
        
        Private Sub OnProporcionar_servicioOperationCompleted(ByVal arg As Object)
            If (Not (Me.Proporcionar_servicioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Proporcionar_servicioCompleted(Me, New Proporcionar_servicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://ln.gesalm.integracion.pronaca.com.ec")>  _
    Partial Public Class SendBalanceData
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://ln.gesalm.integracion.pronaca.com.ec")>  _
    Partial Public Class SendBalanceDataResponse
        
        Private sendBalanceDataResultField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property SendBalanceDataResult() As String
            Get
                Return Me.sendBalanceDataResultField
            End Get
            Set
                Me.sendBalanceDataResultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub Proporcionar_servicioCompletedEventHandler(ByVal sender As Object, ByVal e As Proporcionar_servicioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Proporcionar_servicioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SendBalanceDataResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SendBalanceDataResponse)
            End Get
        End Property
    End Class
End Namespace
